import { zodResolver } from '@hookform/resolvers/zod';
import { Button, Drawer, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { Controller, useForm } from 'react-hook-form';
import { z } from 'zod';
import type { Customer, CustomerOnboardingInput } from '../api/bss';

const schema = z.object({ company_id: z.coerce.number().int().positive(), customer_code: z.string().min(1).max(64), name: z.string().min(1), type: z.enum(['individual', 'organization']), email: z.string().email().optional().or(z.literal('')), phone: z.string().max(64).optional(), address: z.string().optional(), source_id: z.string().optional(), contact_value: z.string().optional(), address_line1: z.string().optional(), legal_name: z.string().optional(), verification_reference: z.string().optional() });
type Form = z.infer<typeof schema>;
export const CustomerFormDrawer = ({ customer, onSubmit, onClose }: { customer?: Customer; onSubmit: (value: CustomerOnboardingInput) => void; onClose: () => void }) => {
    const { control, handleSubmit, register, formState: { errors } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: customer ? { ...customer, email: customer.email || '', phone: customer.phone || '', address: customer.address || '' } : { type: 'individual' } });
    return <Drawer anchor="right" open onClose={onClose}><Stack component="form" onSubmit={handleSubmit(value => onSubmit({ company_id: value.company_id, customer_code: value.customer_code, name: value.name, type: value.type, email: value.email || null, phone: value.phone || null, address: value.address || null, source_id: value.source_id ? Number(value.source_id) : undefined, initial_contact: value.contact_value ? { kind: 'email', value: value.contact_value } : undefined, initial_address: value.address_line1 ? { line1: value.address_line1 } : undefined, business_profile: value.legal_name ? { legal_name: value.legal_name } : undefined, verification: value.verification_reference ? { kind: 'onboarding', status: 'verified', reference: value.verification_reference } : undefined }))} spacing={2} sx={{ p: 3, width: { xs: '100vw', sm: 420 } }}><Typography variant="h6">{customer ? 'Edit customer' : 'New customer onboarding'}</Typography><TextField label="Company ID" type="number" disabled={!!customer} {...register('company_id')} error={!!errors.company_id} helperText={errors.company_id?.message} /><TextField label="Customer code" disabled={!!customer} {...register('customer_code')} /><TextField label="Name" {...register('name')} /><Controller control={control} name="type" render={({ field }) => <TextField {...field} select label="Type"><MenuItem value="individual">Individual</MenuItem><MenuItem value="organization">Organization</MenuItem></TextField>} /><TextField label="Source ID" type="number" {...register('source_id')} /><TextField label="Email" {...register('email')} /><TextField label="Phone" {...register('phone')} /><TextField label="Primary contact email" {...register('contact_value')} /><TextField label="Primary address" {...register('address_line1')} /><TextField label="Legal name" {...register('legal_name')} /><TextField label="Verification reference" {...register('verification_reference')} /><Stack direction="row" spacing={1}><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="contained">Save</Button></Stack></Stack></Drawer>;
};
