<?php

return [
    'permissions' => [
        'assets.create', 'assets.delete', 'assets.dispose', 'assets.export', 'assets.import',
        'assets.lifecycle.create', 'assets.lifecycle.view', 'assets.observations.sync', 'assets.retire', 'assets.transfer', 'assets.update', 'assets.view',
        'audit.view',
        'branches.create', 'branches.delete', 'branches.update', 'branches.view',
        'bss.confirmation.confirm', 'bss.confirmation.create', 'bss.confirmation.decline', 'bss.confirmation.update', 'bss.confirmation.view',
        'bss.customer-services.create', 'bss.customer-services.retire', 'bss.customer-services.update', 'bss.customer-services.view',
        'bss.customers.create', 'bss.customers.retire', 'bss.customers.update', 'bss.customers.view',
        'bss.feasibility.assign', 'bss.feasibility.create', 'bss.feasibility.decide', 'bss.feasibility.evidence.create', 'bss.feasibility.survey.update', 'bss.feasibility.update', 'bss.feasibility.view',
        'bss.leads.convert', 'bss.leads.create', 'bss.leads.update', 'bss.leads.view',
        'bss.services.create', 'bss.services.retire', 'bss.services.update', 'bss.services.view',
        'companies.create', 'companies.delete', 'companies.update', 'companies.view',
        'dashboard.view',
        'departments.create', 'departments.delete', 'departments.update', 'departments.view',
        'designations.create', 'designations.delete', 'designations.update', 'designations.view',
        'employees.create', 'employees.delete', 'employees.update', 'employees.view',
        'fim.cables.create', 'fim.cables.delete', 'fim.cables.update', 'fim.cables.view',
        'fim.connection-points.create', 'fim.connection-points.delete', 'fim.connection-points.update', 'fim.connection-points.view',
        'fim.fiber-cores.create', 'fim.fiber-cores.delete', 'fim.fiber-cores.update', 'fim.fiber-cores.view',
        'fim.fiber-segments.create', 'fim.fiber-segments.delete', 'fim.fiber-segments.update', 'fim.fiber-segments.view',
        'fim.fiber-terminations.create', 'fim.fiber-terminations.delete', 'fim.fiber-terminations.update', 'fim.fiber-terminations.view',
        'fim.passive-optical-ports.create', 'fim.passive-optical-ports.delete', 'fim.passive-optical-ports.update', 'fim.passive-optical-ports.view',
        'fim.physical-connections.create', 'fim.physical-connections.delete', 'fim.physical-connections.update', 'fim.physical-connections.view',
        'fim.splitter-branches.create', 'fim.splitter-branches.delete', 'fim.splitter-branches.view',
        'fim.splitter-profiles.create', 'fim.splitter-profiles.delete', 'fim.splitter-profiles.generate-ports', 'fim.splitter-profiles.update', 'fim.splitter-profiles.view',
        'fim.termination-port-attachments.create', 'fim.termination-port-attachments.delete', 'fim.termination-port-attachments.view',
        'integration.uisp.import', 'integrations.create', 'integrations.credentials.manage', 'integrations.delete', 'integrations.logs.view', 'integrations.sync', 'integrations.test', 'integrations.update', 'integrations.view',
        'librenms.import', 'logs.view',
        'net.network-port-fiber-attachments.create', 'net.network-port-fiber-attachments.delete', 'net.network-port-fiber-attachments.view',
        'net.network-ports.create', 'net.network-ports.delete', 'net.network-ports.update', 'net.network-ports.view',
        'net.pon-domains.create', 'net.pon-domains.delete', 'net.pon-domains.view',
        'net.pon-memberships.create', 'net.pon-memberships.delete', 'net.pon-memberships.view',
        'net.port-switching-configs.configure', 'net.port-switching-configs.delete', 'net.port-switching-configs.view',
        'net.routing-instances.create', 'net.routing-instances.delete', 'net.routing-instances.view',
        'net.routing-l3-interface-addresses.create', 'net.routing-l3-interface-addresses.delete', 'net.routing-l3-interface-addresses.view',
        'net.routing-l3-interfaces.create', 'net.routing-l3-interfaces.delete', 'net.routing-l3-interfaces.view',
        'net.static-routes.create', 'net.static-routes.delete', 'net.static-routes.view',
        'net.vlans.create', 'net.vlans.delete', 'net.vlans.update', 'net.vlans.view',
        'permissions.create', 'permissions.delete', 'permissions.update', 'permissions.view',
        'regions.create', 'regions.delete', 'regions.update', 'regions.view',
        'roles.create', 'roles.delete', 'roles.update', 'roles.view',
        'sites.create', 'sites.delete', 'sites.export', 'sites.import', 'sites.update', 'sites.view',
        'system.config.manage', 'system.config.view', 'system.debug.view', 'system.info.view',
        'users.create', 'users.delete', 'users.update', 'users.view',
    ],

    'managed_roles' => [
        'Super Admin' => 'all',
    ],
];
