import { useState, type ReactNode } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Paper, Select, Stack, Switch, Tab, Tabs, TextField, Typography } from '@mui/material';
import { Circle, MapContainer, TileLayer } from 'react-leaflet';
import { PageHeader } from '@/components/layout/PageHeader';
import { Can } from '@/components/auth/Can';
import { PageErrorState, PageLoadingState } from '@/components/feedback/PageStates';
import { getErrorMessage } from '@/utils';
import { useToast } from '@/components/feedback/ToastProvider';
import { bssKeys } from '@/api/queryKeys';
import { bssApi, type FeasibilityCheck, type FeasibilityOutcome } from '../api/bss';
import 'leaflet/dist/leaflet.css';

const terminal = ['feasible', 'not_feasible', 'cancelled', 'expired'];
const openForSurvey = ['requested', 'reviewing', 'survey_required'];
const openForSurveyCompletion = ['reviewing', 'survey_required', 'survey_scheduled'];
const tabLabels = ['Overview', 'Location', 'Assessment', 'Evidence', 'Survey', 'Conditions', 'Confirmation', 'History'] as const;
type TabKey = typeof tabLabels[number];
const evidenceTypes = ['site_observation', 'asset_observation', 'port_observation', 'fiber_observation', 'pon_observation', 'gis_analysis', 'network_analysis', 'provider_observation', 'manual_observation', 'other'];
const conditionTypes = ['fiber_construction', 'pole_permission', 'equipment_requirement', 'capacity_upgrade', 'additional_survey', 'commercial_approval', 'civil_work', 'permits', 'other'];
const complexityOptions = ['simple', 'moderate', 'complex', 'unknown'];
const channels = ['phone', 'office', 'email', 'portal', 'sales_agent', 'signed_document', 'other'];
const outcomes: FeasibilityOutcome[] = ['feasible', 'conditionally_feasible', 'not_feasible'];

const Row = ({ label, value }: { label: string; value: ReactNode }) => <Box sx={{ display: 'flex', gap: 1, py: 0.5 }}><Typography variant="body2" color="text.secondary" sx={{ minWidth: 210 }}>{label}</Typography><Typography variant="body2">{value || '—'}</Typography></Box>;

export const FeasibilityDetailPage = () => {
    const id = Number(useParams<{ id: string }>().id); const navigate = useNavigate(); const queryClient = useQueryClient(); const { showToast } = useToast();
    const [searchParams, setSearchParams] = useSearchParams(); const tab = (searchParams.get('tab') as TabKey | null) ?? 'Overview';
    const setTab = (value: TabKey) => setSearchParams(value === 'Overview' ? {} : { tab: value });
    const record = useQuery({ queryKey: bssKeys.feasibilityCheck(id), queryFn: () => bssApi.feasibilityCheck(id), enabled: id > 0 });
    const evidence = useQuery({ queryKey: bssKeys.feasibilityEvidence(id), queryFn: () => bssApi.feasibilityEvidence(id), enabled: id > 0 });
    const conditions = useQuery({ queryKey: bssKeys.feasibilityConditions(id), queryFn: () => bssApi.feasibilityConditions(id), enabled: id > 0 });
    const confirmations = useQuery({ queryKey: bssKeys.feasibilityConfirmations(id), queryFn: () => bssApi.feasibilityConfirmations(id), enabled: id > 0 });
    const refresh = () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityCheck(id) }); queryClient.invalidateQueries({ queryKey: ['bss', 'feasibility-checks'] }); queryClient.invalidateQueries({ queryKey: ['bss', 'leads'] }); };
    const onError = (error: Error) => showToast(getErrorMessage(error), 'error');
    const runMutate = (mutation: () => Promise<unknown>, message: string) => (mutation().then(() => { refresh(); showToast(message, 'success'); }).catch(onError));

    const [decideOpen, setDecideOpen] = useState(false); const [decideForm, setDecideForm] = useState({ outcome: '', valid_until: '', conditions_summary: '', estimated_work_summary: '', decision_summary: '' });
    const decide = useMutation({ mutationFn: () => bssApi.decideFeasibility(id, { ...decideForm, outcome: decideForm.outcome as FeasibilityOutcome, ...(decideForm.valid_until ? { valid_until: decideForm.valid_until } : {}) }), onSuccess: () => { refresh(); showToast('Decision recorded.', 'success'); setDecideOpen(false); }, onError });
    const startAction = useMutation({ mutationFn: () => bssApi.startFeasibilityAssessment(id), onSuccess: () => { refresh(); showToast('Assessment started.', 'success'); }, onError });
    const assign = useMutation({ mutationFn: (userId: number) => bssApi.assignFeasibility(id, userId), onSuccess: () => { refresh(); showToast('Assessor assigned.', 'success'); }, onError });
    const [assessorId, setAssessorId] = useState('');

    const [assessmentForm, setAssessmentForm] = useState({ assessment_method: '', internal_notes: '', customer_safe_summary: '' });
    const saveAssessment = useMutation({ mutationFn: () => bssApi.updateFeasibility(id, { ...(assessmentForm.assessment_method ? { assessment_method: assessmentForm.assessment_method } : {}), ...(assessmentForm.internal_notes ? { internal_notes: assessmentForm.internal_notes } : {}), ...(assessmentForm.customer_safe_summary ? { customer_safe_summary: assessmentForm.customer_safe_summary } : {}) }), onSuccess: () => { refresh(); showToast('Assessment details saved.', 'success'); }, onError });

    const [surveyOpen, setSurveyOpen] = useState(false); const [surveyForm, setSurveyForm] = useState({ scheduled_at: '', assigned_to: '' });
    const startSurvey = useMutation({ mutationFn: () => bssApi.startFeasibilitySurvey(id, { ...(surveyForm.scheduled_at ? { scheduled_at: surveyForm.scheduled_at } : {}), ...(surveyForm.assigned_to ? { assigned_to: Number(surveyForm.assigned_to) } : {}) }), onSuccess: () => { refresh(); setSurveyOpen(false); showToast('Survey started.', 'success'); }, onError });

    const [completeOpen, setCompleteOpen] = useState(false); const [completeForm, setCompleteForm] = useState({ location_verified: false, coordinates_verified_lat: '', coordinates_verified_lng: '', nearest_infrastructure_notes: '', access_path_notes: '', civil_work_required: false, installation_complexity: '', signal_observations: '', survey_notes: '', findings: '', recommended_outcome: '' });
    const completeSurvey = useMutation({ mutationFn: () => bssApi.completeFeasibilitySurvey(id, { ...(completeForm.location_verified ? { location_verified: true } : {}), ...(completeForm.civil_work_required ? { civil_work_required: true } : {}), ...(completeForm.coordinates_verified_lat ? { coordinates_verified_lat: Number(completeForm.coordinates_verified_lat) } : {}), ...(completeForm.coordinates_verified_lng ? { coordinates_verified_lng: Number(completeForm.coordinates_verified_lng) } : {}), ...(completeForm.nearest_infrastructure_notes ? { nearest_infrastructure_notes: completeForm.nearest_infrastructure_notes } : {}), ...(completeForm.access_path_notes ? { access_path_notes: completeForm.access_path_notes } : {}), ...(completeForm.installation_complexity ? { installation_complexity: completeForm.installation_complexity } : {}), ...(completeForm.signal_observations ? { signal_observations: completeForm.signal_observations } : {}), ...(completeForm.survey_notes ? { survey_notes: completeForm.survey_notes } : {}), ...(completeForm.findings ? { findings: completeForm.findings } : {}), ...(completeForm.recommended_outcome ? { recommended_outcome: completeForm.recommended_outcome } : {}) }), onSuccess: () => { refresh(); setCompleteOpen(false); showToast('Survey completed.', 'success'); }, onError });

    const [evidenceForm, setEvidenceForm] = useState({ evidence_type: '', referenced_entity_type: '', referenced_entity_id: '', observation_summary: '' });
    const addEvidence = useMutation({ mutationFn: () => bssApi.addFeasibilityEvidence(id, { evidence_type: evidenceForm.evidence_type, observation_summary: evidenceForm.observation_summary, ...(evidenceForm.referenced_entity_type ? { referenced_entity_type: evidenceForm.referenced_entity_type } : {}), ...(evidenceForm.referenced_entity_type && evidenceForm.referenced_entity_id ? { referenced_entity_id: Number(evidenceForm.referenced_entity_id) } : {}) }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityEvidence(id) }); refresh(); setEvidenceForm({ evidence_type: '', referenced_entity_type: '', referenced_entity_id: '', observation_summary: '' }); showToast('Evidence recorded.', 'success'); }, onError });

    const [conditionForm, setConditionForm] = useState({ condition_type: '', description: '', is_mandatory: false });
    const addCondition = useMutation({ mutationFn: () => bssApi.addFeasibilityCondition(id, { condition_type: conditionForm.condition_type, description: conditionForm.description, is_mandatory: conditionForm.is_mandatory }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityConditions(id) }); refresh(); setConditionForm({ condition_type: '', description: '', is_mandatory: false }); showToast('Condition added.', 'success'); }, onError });
    const resolveCondition = useMutation({ mutationFn: ({ conditionId, status, resolution_notes }: { conditionId: number; status: 'resolved' | 'waived' | 'not_applicable'; resolution_notes: string }) => bssApi.resolveFeasibilityCondition(conditionId, { status, resolution_notes }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityConditions(id) }); refresh(); showToast('Condition updated.', 'success'); }, onError });

    const [confirmationForm, setConfirmationForm] = useState({ channel: '', presented_summary: '', notes: '' });
    const recordConfirmation = useMutation({ mutationFn: () => bssApi.createFeasibilityConfirmation(id, confirmationForm), onSuccess: () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityConfirmations(id) }); refresh(); showToast('Confirmation recorded.', 'success'); }, onError });
    const confirmCustomer = useMutation({ mutationFn: (confirmationId: number) => bssApi.confirmCustomerConfirmation(confirmationId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityConfirmations(id) }); refresh(); showToast('Customer confirmation recorded.', 'success'); }, onError });
    const declineCustomer = useMutation({ mutationFn: (confirmationId: number) => bssApi.declineCustomerConfirmation(confirmationId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: bssKeys.feasibilityConfirmations(id) }); refresh(); showToast('Confirmation declined.', 'success'); }, onError });

    if (record.isLoading) return <PageLoadingState label="Loading feasibility check..." />;
    if (record.error || !record.data) return <PageErrorState message="Feasibility check is unavailable or outside your management scope." onRetry={() => record.refetch()} />;
    const check: FeasibilityCheck = record.data;
    const subject = check.lead?.name ?? check.customer?.name ?? `Company #${check.company_id}`;
    return <Box>
        <PageHeader title={check.feasibility_code} subtitle={`${subject} · ${check.status}${check.outcome ? ` · ${check.outcome}` : ''}`} breadcrumbs={[{ label: 'BSS', path: '/bss' }, { label: 'Feasibility', path: '/bss/feasibility' }]} actions={<><Button onClick={() => navigate('/bss/feasibility')}>Back</Button>{!terminal.includes(check.status) && <Can permission="bss.feasibility.update"><Button variant="contained" disabled={startAction.isPending} onClick={() => runMutate(startAction.mutateAsync, 'Assessment started.')}>Start assessment</Button></Can>}{!terminal.includes(check.status) && <Can permission="bss.feasibility.decide"><Button variant="contained" color="success" sx={{ ml: 1 }} disabled={check.status === 'requested'} onClick={() => setDecideOpen(true)}>Record decision</Button></Can>}{openForSurvey.includes(check.status) && <Can permission="bss.feasibility.survey.update"><Button color="primary" variant="outlined" sx={{ ml: 1 }} onClick={() => setSurveyOpen(true)}>Start survey</Button></Can>}{openForSurveyCompletion.includes(check.status) && <Can permission="bss.feasibility.survey.update"><Button color="primary" variant="outlined" sx={{ ml: 1 }} onClick={() => setCompleteOpen(true)}>Complete survey</Button></Can>}{check.status === 'feasible' && !check.confirmation && <Can permission="bss.confirmation.create"><Button color="secondary" variant="outlined" sx={{ ml: 1 }} onClick={() => setTab('Confirmation')}>Record confirmation</Button></Can>}</>} />
        <Tabs value={tab} onChange={(_, value: TabKey) => setTab(value)} sx={{ mb: 2 }}>{tabLabels.map(label => <Tab key={label} label={label} value={label} />)}</Tabs>
        {tab === 'Overview' && <Stack spacing={2}><Card><CardContent><Row label="Feasibility code" value={check.feasibility_code} /><Row label="Status" value={check.status} /><Row label="Outcome" value={check.outcome} /><Row label="Requested service" value={check.requested_service_summary} /><Row label="Requested location" value={check.requested_location_summary} /><Row label="Requested coordinates" value={check.requested_location_lat !== null && check.requested_location_lng !== null ? `${check.requested_location_lat}, ${check.requested_location_lng}` : null} /><Row label="Requested at" value={check.requested_at ? new Date(check.requested_at).toLocaleString() : null} /><Row label="Valid until" value={check.valid_until ? new Date(check.valid_until).toLocaleDateString() : null} /><Row label="Lead" value={check.lead ? `${check.lead.lead_code} · ${check.lead.name} (${check.lead.status})` : null} /><Row label="Customer" value={check.customer ? `${check.customer.customer_code} · ${check.customer.name}` : null} /><Row label="Assessor" value={check.assigned_assessor?.name ?? 'Unassigned'} /></CardContent></Card>{check.confirmation && <Card><CardContent><Typography fontWeight={600} sx={{ mb: 1 }}>Customer confirmation</Typography><Row label="Reference" value={check.confirmation.reference_code} /><Row label="Channel" value={check.confirmation.channel} /><Row label="Status" value={check.confirmation.status} /><Row label="Presented summary" value={check.confirmation.presented_summary} /><Row label="Confirmed at" value={check.confirmation.confirmed_at ? new Date(check.confirmation.confirmed_at).toLocaleString() : null} /></CardContent></Card>}</Stack>}
        {tab === 'Location' && check.requested_location_lat !== null && check.requested_location_lng !== null ? <Paper sx={{ height: 560, overflow: 'hidden' }}><MapContainer center={[check.requested_location_lat, check.requested_location_lng]} zoom={18} style={{ height: '100%', width: '100%' }}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Circle center={[check.requested_location_lat, check.requested_location_lng]} radius={50} /></MapContainer></Paper> : <PageErrorState message="No coordinates were captured for this feasibility check." onRetry={() => undefined} />}
        {tab === 'Assessment' && <Stack spacing={2}><Card><CardContent><Row label="Assessment method" value={check.assessment_method} /><Row label="Assessment started" value={check.assessment_started_at ? new Date(check.assessment_started_at).toLocaleString() : null} /><Row label="Internal notes" value={check.internal_notes} /><Row label="Customer-safe summary" value={check.customer_safe_summary} /><Row label="Conditions summary" value={check.conditions_summary} /><Row label="Estimated work" value={check.estimated_work_summary} /></CardContent></Card><Can permission="bss.feasibility.assign"><Card><CardContent><Typography fontWeight={600} sx={{ mb: 1 }}>Assign assessor</Typography><Stack direction="row" spacing={1} alignItems="center"><TextField size="small" label="Assessor user ID" type="number" value={assessorId} onChange={event => setAssessorId(event.target.value)} /><Button variant="contained" size="small" disabled={assign.isPending || !assessorId} onClick={() => { const value = Number(assessorId); if (value > 0) assign.mutate(value); }}>Assign</Button></Stack></CardContent></Card></Can><Can permission="bss.feasibility.update"><Card><CardContent><Typography fontWeight={600} sx={{ mb: 1 }}>Update assessment details</Typography><Select size="small" displayEmpty value={assessmentForm.assessment_method} onChange={event => setAssessmentForm({ ...assessmentForm, assessment_method: event.target.value })} sx={{ minWidth: 220, mr: 1 }}><MenuItem value="">Method…</MenuItem>{['desk_review', 'gis_review', 'network_review', 'field_survey', 'hybrid', 'other'].map(method => <MenuItem key={method} value={method}>{method}</MenuItem>)}</Select><TextField size="small" label="Internal notes" value={assessmentForm.internal_notes} onChange={event => setAssessmentForm({ ...assessmentForm, internal_notes: event.target.value })} fullWidth multiline minRows={2} sx={{ mt: 1 }} /><TextField size="small" label="Customer-safe summary" value={assessmentForm.customer_safe_summary} onChange={event => setAssessmentForm({ ...assessmentForm, customer_safe_summary: event.target.value })} fullWidth multiline minRows={2} sx={{ mt: 1 }} /><Button variant="contained" sx={{ mt: 1 }} disabled={saveAssessment.isPending} onClick={() => saveAssessment.mutate()}>Save assessment details</Button></CardContent></Card></Can></Stack>}
        {tab === 'Evidence' && <Stack spacing={2}><Card><CardContent><Typography fontWeight={600} sx={{ mb: 1 }}>Record evidence</Typography><Select size="small" displayEmpty value={evidenceForm.evidence_type} onChange={event => setEvidenceForm({ ...evidenceForm, evidence_type: event.target.value })} sx={{ minWidth: 220, mr: 1 }}><MenuItem value="">Evidence type…</MenuItem>{evidenceTypes.map(type => <MenuItem key={type} value={type}>{type}</MenuItem>)}</Select><Select size="small" displayEmpty value={evidenceForm.referenced_entity_type} onChange={event => setEvidenceForm({ ...evidenceForm, referenced_entity_type: event.target.value })} sx={{ minWidth: 220, mr: 1 }}><MenuItem value="">Referenced entity…</MenuItem>{['Site', 'Asset', 'NetworkPort', 'PonDomain', 'PassiveOpticalPort', 'FiberTermination', 'NetworkConnectionPoint', 'FiberCable', 'FiberSegment'].map(entity => <MenuItem key={entity} value={entity}>{entity}</MenuItem>)}</Select><TextField size="small" label="Entity ID" type="number" value={evidenceForm.referenced_entity_id} onChange={event => setEvidenceForm({ ...evidenceForm, referenced_entity_id: event.target.value })} sx={{ width: 120 }} /><TextField size="small" label="Observation summary" value={evidenceForm.observation_summary} onChange={event => setEvidenceForm({ ...evidenceForm, observation_summary: event.target.value })} fullWidth multiline minRows={2} sx={{ mt: 1 }} /><Button variant="contained" sx={{ mt: 1 }} disabled={addEvidence.isPending || !evidenceForm.evidence_type || !evidenceForm.observation_summary} onClick={() => addEvidence.mutate()}>Add evidence</Button></CardContent></Card>{evidence.data?.map(item => <Card key={item.id}><CardContent><Row label="Type" value={item.evidence_type} /><Row label="Referenced" value={item.referenced_entity_type && item.referenced_entity_id ? `${item.referenced_entity_type} #${item.referenced_entity_id}` : 'None' } /><Row label="Recorded by" value={item.recorded_by_name} /><Row label="Recorded at" value={new Date(item.recorded_at).toLocaleString()} /><Typography variant="body2" sx={{ mt: 1 }}>{item.observation_summary}</Typography></CardContent></Card>)}</Stack>}
        {tab === 'Survey' && (check.survey ? <Stack spacing={2}><Card><CardContent><Row label="Survey status" value={check.survey.status} /><Row label="Assigned to" value={check.survey.assigned_to_name} /><Row label="Requested at" value={check.survey.requested_at ? new Date(check.survey.requested_at).toLocaleString() : null} /><Row label="Scheduled at" value={check.survey.scheduled_at ? new Date(check.survey.scheduled_at).toLocaleString() : null} /><Row label="Started at" value={check.survey.started_at ? new Date(check.survey.started_at).toLocaleString() : null} /><Row label="Completed at" value={check.survey.completed_at ? new Date(check.survey.completed_at).toLocaleString() : null} /><Row label="Location verified" value={check.survey.location_verified ? 'Yes' : 'No'} /><Row label="Verified coordinates" value={check.survey.coordinates_verified_lat !== null ? `${check.survey.coordinates_verified_lat}, ${check.survey.coordinates_verified_lng}` : null} /><Row label="Civil work required" value={check.survey.civil_work_required ? 'Yes' : 'No'} /><Row label="Installation complexity" value={check.survey.installation_complexity} /><Row label="Recommended outcome" value={check.survey.recommended_outcome} /><Typography variant="body2" sx={{ mt: 1 }}>{check.survey.findings}</Typography></CardContent></Card></Stack> : <PageEmptyState message="No survey has been requested for this feasibility check." />)}
        {tab === 'Conditions' && <Stack spacing={2}><Can permission="bss.feasibility.update"><Card><CardContent><Typography fontWeight={600} sx={{ mb: 1 }}>Add condition</Typography><Select size="small" displayEmpty value={conditionForm.condition_type} onChange={event => setConditionForm({ ...conditionForm, condition_type: event.target.value })} sx={{ minWidth: 240, mr: 1 }}><MenuItem value="">Condition type…</MenuItem>{conditionTypes.map(type => <MenuItem key={type} value={type}>{type}</MenuItem>)}</Select><FormControlLabel control={<Switch checked={conditionForm.is_mandatory} onChange={event => setConditionForm({ ...conditionForm, is_mandatory: event.target.checked })} />} label="Mandatory" /><TextField size="small" label="Description" value={conditionForm.description} onChange={event => setConditionForm({ ...conditionForm, description: event.target.value })} fullWidth multiline minRows={2} sx={{ mt: 1 }} /><Button variant="contained" sx={{ mt: 1 }} disabled={addCondition.isPending || !conditionForm.condition_type || !conditionForm.description} onClick={() => addCondition.mutate()}>Add condition</Button></CardContent></Card></Can>{conditions.data?.map(condition => <Card key={condition.id}><CardContent><Stack direction="row" spacing={1} sx={{ mb: 1 }} alignItems="center"><Chip size="small" label={condition.status} /><Typography fontWeight={600}>{condition.condition_type}</Typography>{condition.is_mandatory && <Chip size="small" label="mandatory" color="warning" />}</Stack><Typography variant="body2" sx={{ mb: 1 }}>{condition.description}</Typography>{['pending', 'in_progress'].includes(condition.status) && <Can permission="bss.feasibility.update"><Stack direction="row" spacing={1} alignItems="center"><Select size="small" displayEmpty defaultValue="" onChange={event => { const notes = window.prompt('Resolution notes (optional)'); resolveCondition.mutate({ conditionId: condition.id, status: event.target.value as 'resolved' | 'waived' | 'not_applicable', resolution_notes: notes ?? '' }); }} sx={{ minWidth: 160 }}><MenuItem value="" disabled>Resolve…</MenuItem><MenuItem value="resolved">Resolved</MenuItem><MenuItem value="waived">Waived</MenuItem><MenuItem value="not_applicable">Not applicable</MenuItem></Select></Stack></Can>}<Row label="Resolution notes" value={condition.resolution_notes} /><Row label="Resolved by" value={condition.resolved_by_name} /><Row label="Resolved at" value={condition.resolved_at ? new Date(condition.resolved_at).toLocaleString() : null} /></CardContent></Card>)}</Stack>}
        {tab === 'Confirmation' && <Stack spacing={2}><Card><CardContent><Typography fontWeight={600} sx={{ mb: 1 }}>Record confirmation</Typography><Select size="small" displayEmpty value={confirmationForm.channel} onChange={event => setConfirmationForm({ ...confirmationForm, channel: event.target.value })} sx={{ minWidth: 220, mr: 1 }}><MenuItem value="">Channel…</MenuItem>{channels.map(channel => <MenuItem key={channel} value={channel}>{channel}</MenuItem>)}</Select><TextField size="small" label="Presented summary" value={confirmationForm.presented_summary} onChange={event => setConfirmationForm({ ...confirmationForm, presented_summary: event.target.value })} fullWidth multiline minRows={2} sx={{ mt: 1 }} /><TextField size="small" label="Notes" value={confirmationForm.notes} onChange={event => setConfirmationForm({ ...confirmationForm, notes: event.target.value })} fullWidth sx={{ mt: 1 }} /><Button variant="contained" sx={{ mt: 1 }} disabled={recordConfirmation.isPending || !confirmationForm.channel || !confirmationForm.presented_summary} onClick={() => recordConfirmation.mutate()}>Record confirmation</Button></CardContent></Card>{confirmations.data?.map(c => <Card key={c.id}><CardContent><Row label="Reference code" value={c.reference_code} /><Row label="Channel" value={c.channel} /><Row label="Status" value={c.status} /><Row label="Recorded by" value={c.recorded_by_name} /><Row label="Presented summary" value={c.presented_summary} /><Typography variant="body2" sx={{ mt: 1 }}>{c.notes}</Typography>{c.status === 'pending' && <Stack direction="row" spacing={1} sx={{ mt: 1 }}><Can permission="bss.confirmation.confirm"><Button variant="contained" color="success" size="small" onClick={() => confirmCustomer.mutate(c.id)}>Confirm</Button></Can><Can permission="bss.confirmation.decline"><Button color="error" size="small" onClick={() => declineCustomer.mutate(c.id)}>Decline</Button></Can></Stack>}</CardContent></Card>)}</Stack>}
        {tab === 'History' && <Stack spacing={1}>{(check.lifecycle_history || []).map(entry => <Card key={entry.id}><CardContent><Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}><Chip size="small" label={entry.from_status || '—'} /><Typography variant="body2">→</Typography><Chip size="small" label={entry.to_status} /><Typography variant="caption" color="text.secondary">{entry.to_outcome ? ` · outcome ${entry.to_outcome}` : ''}</Typography></Stack><Typography variant="caption" color="text.secondary">{entry.actor ?? 'System'} · {new Date(entry.created_at).toLocaleString()}</Typography></CardContent></Card>)}{!check.lifecycle_history?.length && <PageEmptyState message="No lifecycle events recorded." />}</Stack>}
        <Dialog open={decideOpen} onClose={() => setDecideOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Record decision</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Select displayEmpty value={decideForm.outcome} onChange={event => setDecideForm({ ...decideForm, outcome: event.target.value })}><MenuItem value="" disabled>Outcome…</MenuItem>{outcomes.map(outcome => <MenuItem key={outcome} value={outcome}>{outcome}</MenuItem>)}</Select><TextField label="Valid until" type="date" value={decideForm.valid_until} onChange={event => setDecideForm({ ...decideForm, valid_until: event.target.value })} /><TextField label="Conditions summary" value={decideForm.conditions_summary} onChange={event => setDecideForm({ ...decideForm, conditions_summary: event.target.value })} multiline minRows={2} /><TextField label="Estimated work summary" value={decideForm.estimated_work_summary} onChange={event => setDecideForm({ ...decideForm, estimated_work_summary: event.target.value })} multiline minRows={2} /><TextField label="Decision summary" value={decideForm.decision_summary} onChange={event => setDecideForm({ ...decideForm, decision_summary: event.target.value })} multiline minRows={2} /></Stack></DialogContent><DialogActions><Button onClick={() => setDecideOpen(false)}>Cancel</Button><Button variant="contained" disabled={decide.isPending || !decideForm.outcome} onClick={() => decide.mutate()}>Record decision</Button></DialogActions></Dialog>
        <Dialog open={surveyOpen} onClose={() => setSurveyOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Start survey</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Assigned user ID" type="number" value={surveyForm.assigned_to} onChange={event => setSurveyForm({ ...surveyForm, assigned_to: event.target.value })} /><TextField label="Scheduled at" type="datetime-local" value={surveyForm.scheduled_at} onChange={event => setSurveyForm({ ...surveyForm, scheduled_at: event.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setSurveyOpen(false)}>Cancel</Button><Button variant="contained" disabled={startSurvey.isPending} onClick={() => startSurvey.mutate()}>Start survey</Button></DialogActions></Dialog>
        <Dialog open={completeOpen} onClose={() => setCompleteOpen(false)} fullWidth maxWidth="md"><DialogTitle>Complete survey</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><FormControlLabel control={<Switch checked={completeForm.location_verified} onChange={event => setCompleteForm({ ...completeForm, location_verified: event.target.checked })} />} label="Location verified" /><Stack direction="row" spacing={1}><TextField label="Verified latitude" type="number" value={completeForm.coordinates_verified_lat} onChange={event => setCompleteForm({ ...completeForm, coordinates_verified_lat: event.target.value })} /><TextField label="Verified longitude" type="number" value={completeForm.coordinates_verified_lng} onChange={event => setCompleteForm({ ...completeForm, coordinates_verified_lng: event.target.value })} /></Stack><TextField label="Nearest infrastructure notes" value={completeForm.nearest_infrastructure_notes} onChange={event => setCompleteForm({ ...completeForm, nearest_infrastructure_notes: event.target.value })} multiline minRows={2} /><TextField label="Access path notes" value={completeForm.access_path_notes} onChange={event => setCompleteForm({ ...completeForm, access_path_notes: event.target.value })} multiline minRows={2} /><FormControlLabel control={<Switch checked={completeForm.civil_work_required} onChange={event => setCompleteForm({ ...completeForm, civil_work_required: event.target.checked })} />} label="Civil work required" /><Select displayEmpty value={completeForm.installation_complexity} onChange={event => setCompleteForm({ ...completeForm, installation_complexity: event.target.value })}><MenuItem value="" disabled>Installation complexity…</MenuItem>{complexityOptions.map(option => <MenuItem key={option} value={option}>{option}</MenuItem>)}</Select><TextField label="Signal observations" value={completeForm.signal_observations} onChange={event => setCompleteForm({ ...completeForm, signal_observations: event.target.value })} multiline minRows={2} /><TextField label="Survey notes" value={completeForm.survey_notes} onChange={event => setCompleteForm({ ...completeForm, survey_notes: event.target.value })} multiline minRows={2} /><TextField label="Findings" value={completeForm.findings} onChange={event => setCompleteForm({ ...completeForm, findings: event.target.value })} multiline minRows={2} /><Select displayEmpty value={completeForm.recommended_outcome} onChange={event => setCompleteForm({ ...completeForm, recommended_outcome: event.target.value })}><MenuItem value="" disabled>Recommended outcome…</MenuItem>{outcomes.map(outcome => <MenuItem key={outcome} value={outcome}>{outcome}</MenuItem>)}</Select></Stack></DialogContent><DialogActions><Button onClick={() => setCompleteOpen(false)}>Cancel</Button><Button variant="contained" disabled={completeSurvey.isPending} onClick={() => completeSurvey.mutate()}>Complete survey</Button></DialogActions></Dialog>
    </Box>;
};

const PageEmptyState = ({ message }: { message: string }) => <Typography color="text.secondary" sx={{ py: 4, textAlign: 'center' }}>{message}</Typography>;

export default FeasibilityDetailPage;