import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField, Typography } from '@mui/material';
import { PageHeader } from '@/components/layout/PageHeader';
import { Can } from '@/components/auth/Can';
import { PageErrorState, PageLoadingState, PageEmptyState } from '@/components/feedback/PageStates';
import { useToast } from '@/components/feedback/ToastProvider';
import { getErrorMessage } from '@/utils';
import { bssKeys } from '@/api/queryKeys';
import { bssApi, type FeasibilityCheck } from '../api/bss';

const feasibilityTint = (status: string) => status === 'feasible' ? 'success' : status === 'not_feasible' || status === 'cancelled' || status === 'expired' ? 'error' : status === 'conditionally_feasible' ? 'info' : 'warning';

export const LeadDetailPage = () => {
    const id = Number(useParams<{ id: string }>().id); const navigate = useNavigate(); const queryClient = useQueryClient(); const { showToast } = useToast(); const [qualification, setQualification] = useState('{"serviceable": true}'); const [code, setCode] = useState('');
    const [feasibilityOpen, setFeasibilityOpen] = useState(false); const [feasibilityForm, setFeasibilityForm] = useState({ requested_service_summary: '', requested_location_summary: '', requested_location_lat: '', requested_location_lng: '' });
    const lead = useQuery({ queryKey: bssKeys.lead(id), queryFn: () => bssApi.lead(id), enabled: id > 0 });
    const candidates = useQuery({ queryKey: ['bss', 'lead-candidates', id], queryFn: () => bssApi.duplicateCandidates(id), enabled: !!lead.data && lead.data.status === 'qualified' });
    const feasibilityChecks = useQuery({ queryKey: bssKeys.leadFeasibility(id), queryFn: () => bssApi.leadFeasibility(id), enabled: id > 0 });
    const refresh = () => { queryClient.invalidateQueries({ queryKey: bssKeys.lead(id) }); queryClient.invalidateQueries({ queryKey: ['bss', 'leads'] }); queryClient.invalidateQueries({ queryKey: bssKeys.leadFeasibility(id) }); };
    const action = useMutation<unknown, Error, 'qualify' | 'unqualify' | 'lose' | 'convert'>({ mutationFn: (kind) => kind === 'qualify' ? bssApi.qualifyLead(id, JSON.parse(qualification) as Record<string, unknown>) : kind === 'unqualify' ? bssApi.unqualifyLead(id) : kind === 'lose' ? bssApi.loseLead(id) : bssApi.convertLead(id, code), onSuccess: () => { refresh(); showToast('Lead lifecycle updated.', 'success'); }, onError: error => showToast(getErrorMessage(error), 'error') });
    const requestFeasibility = useMutation({ mutationFn: () => bssApi.createFeasibility({ lead_id: id, requested_service_summary: feasibilityForm.requested_service_summary, ...(feasibilityForm.requested_location_summary ? { requested_location_summary: feasibilityForm.requested_location_summary } : {}), ...(feasibilityForm.requested_location_lat !== '' && feasibilityForm.requested_location_lng !== '' ? { requested_location_lat: Number(feasibilityForm.requested_location_lat), requested_location_lng: Number(feasibilityForm.requested_location_lng) } : {}) }), onSuccess: record => { refresh(); showToast('Feasibility check requested.', 'success'); setFeasibilityOpen(false); navigate(`/bss/feasibility/${record.id}`); }, onError: error => showToast(getErrorMessage(error), 'error') });
    if (lead.isLoading) return <PageLoadingState label="Loading lead..." />;
    if (lead.error || !lead.data) return <PageErrorState message="Lead is unavailable or outside your management scope." onRetry={() => lead.refetch()} />;
    const record = lead.data;
    return <Box><PageHeader title={record.name} subtitle={`${record.lead_code} · ${record.status}`} breadcrumbs={[{ label: 'BSS', path: '/bss' }, { label: 'Lead' }]} actions={<><Button onClick={() => navigate('/bss/leads')}>Back</Button>{record.status === 'qualified' && <Can permission="bss.feasibility.create"><Button variant="contained" sx={{ ml: 1 }} onClick={() => setFeasibilityOpen(true)}>Request feasibility</Button></Can>}</>} /><Stack spacing={2}><Card><CardContent><Typography>{record.email || 'No email'} · {record.phone || 'No phone'}</Typography><Typography color="text.secondary">Company #{record.company_id}</Typography></CardContent></Card>{record.status === 'new' && <Can permission="bss.leads.update"><Card><CardContent><TextField fullWidth label="Qualification JSON" value={qualification} onChange={event => setQualification(event.target.value)} /><Button sx={{ mt: 1 }} variant="contained" onClick={() => action.mutate('qualify')}>Verify and qualify</Button><Button sx={{ mt: 1, ml: 1 }} color="error" onClick={() => action.mutate('lose')}>Mark lost</Button></CardContent></Card></Can>}{record.status === 'qualified' && <Can permission="bss.leads.convert"><Card><CardContent><Typography variant="h6">Duplicate candidates</Typography>{candidates.data?.map(candidate => <Typography key={candidate.id}>{candidate.customer_code} · {candidate.name}</Typography>)}<TextField sx={{ mt: 1 }} label="New customer code" value={code} onChange={event => setCode(event.target.value)} /><Stack direction="row" spacing={1} sx={{ mt: 1 }}><Button variant="contained" disabled={!code} onClick={() => action.mutate('convert')}>Convert</Button><Can permission="bss.leads.update"><Button onClick={() => action.mutate('unqualify')}>Unqualify</Button><Button color="error" onClick={() => action.mutate('lose')}>Mark lost</Button></Can></Stack></CardContent></Card></Can>}<Card><CardContent><Typography variant="h6">Feasibility checks</Typography>{feasibilityChecks.data?.length ? feasibilityChecks.data.map((check: FeasibilityCheck) => <Box key={check.id} sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', py: 1, cursor: 'pointer' }} onClick={() => navigate(`/bss/feasibility/${check.id}`)}><Box><Typography fontWeight={600}>{check.feasibility_code}</Typography><Typography variant="body2" color="text.secondary">{check.requested_service_summary}</Typography></Box><Chip size="small" label={check.outcome ?? check.status} color={feasibilityTint(check.status)} /></Box>) : <PageEmptyState message="No feasibility checks have been requested for this lead." />}</CardContent></Card></Stack>
        <Dialog open={feasibilityOpen} onClose={() => setFeasibilityOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Request feasibility</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField required label="Requested service summary" value={feasibilityForm.requested_service_summary} onChange={event => setFeasibilityForm({ ...feasibilityForm, requested_service_summary: event.target.value })} multiline minRows={2} /><TextField label="Requested location summary" value={feasibilityForm.requested_location_summary} onChange={event => setFeasibilityForm({ ...feasibilityForm, requested_location_summary: event.target.value })} multiline minRows={2} /><Stack direction="row" spacing={1}><TextField label="Latitude" type="number" value={feasibilityForm.requested_location_lat} onChange={event => setFeasibilityForm({ ...feasibilityForm, requested_location_lat: event.target.value })} /><TextField label="Longitude" type="number" value={feasibilityForm.requested_location_lng} onChange={event => setFeasibilityForm({ ...feasibilityForm, requested_location_lng: event.target.value })} /></Stack></Stack></DialogContent><DialogActions><Button onClick={() => setFeasibilityOpen(false)}>Cancel</Button><Button variant="contained" disabled={requestFeasibility.isPending || !feasibilityForm.requested_service_summary} onClick={() => requestFeasibility.mutate()}>Create feasibility check</Button></DialogActions></Dialog>
    </Box>;
};
export default LeadDetailPage;
