import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { PageHeader } from '@/components/layout/PageHeader';
import { DataTable, type Column } from '@/components/tables/DataTable';
import { PageErrorState } from '@/components/feedback/PageStates';
import { Can } from '@/components/auth/Can';
import { fimApi, type ConnectionPoint, type FiberCable, type FiberCore } from '../api/fim';
import { fimKeys } from '@/api/queryKeys';
import toast from 'react-hot-toast';

type TabName = 'cables' | 'points' | 'segments' | 'cores' | 'connections' | 'operations';
const permissions: Record<Exclude<TabName, 'operations'>, string> = { cables: 'fim.cables.view', points: 'fim.connection-points.view', segments: 'fim.fiber-segments.view', cores: 'fim.fiber-cores.view', connections: 'fim.physical-connections.view' };
const number = (value: FormDataEntryValue | null) => Number(value);

export default function FimOperationsPage() {
    const [tab, setTab] = useState<TabName>('cables'); const [open, setOpen] = useState(false); const [selectedCore, setSelectedCore] = useState<FiberCore | null>(null); const [assetId, setAssetId] = useState('');
    const qc = useQueryClient(); const query = <T,>(key: readonly unknown[], fn: () => Promise<T>) => useQuery({ queryKey: key, queryFn: fn });
    const cables = query(fimKeys.cables({ per_page: 100 }), () => fimApi.cables({ per_page: 100 }));
    const points = query(fimKeys.points({ per_page: 100 }), () => fimApi.points({ per_page: 100 }));
    const segments = query(fimKeys.segments({ per_page: 100 }), () => fimApi.segments({ per_page: 100 }));
    const cores = query(fimKeys.cores({ per_page: 100 }), () => fimApi.cores({ per_page: 100 }));
    const connections = query(fimKeys.connections({ per_page: 100 }), () => fimApi.connections({ per_page: 100 }));
    const passive = query(fimKeys.passivePorts(Number(assetId) || 0, { per_page: 100 }), () => assetId ? fimApi.passivePorts(Number(assetId), { per_page: 100 }) : Promise.resolve({ data: [] }));
    const mutate = useMutation<unknown, Error, { kind: string; data: Record<string, unknown> }>({ mutationFn: (payload) => {
        if (payload.kind === 'point') return fimApi.createPoint(payload.data); if (payload.kind === 'segment') return fimApi.createSegment(payload.data); if (payload.kind === 'core') return fimApi.createCore(payload.data); if (payload.kind === 'termination') return fimApi.createTermination(Number(payload.data.fiber_core_id), payload.data); if (payload.kind === 'connection') return fimApi.createConnection(payload.data); return fimApi.createPassivePort(Number(payload.data.asset_id), payload.data);
    }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['fim'] }); setOpen(false); toast.success('Physical record created.'); }, onError: () => toast.error('The API rejected this physical record. Review the selected authoritative endpoints.') });
    const hasError = cables.isError || points.isError || segments.isError || cores.isError || connections.isError;
    const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const kind = String(f.get('kind')); const data: Record<string, unknown> = Object.fromEntries(f.entries()); delete data.kind; Object.keys(data).forEach(k => { if (data[k] === '') delete data[k]; }); Object.keys(data).forEach(k => { if (/_id$/.test(k) || ['sequence', 'core_number'].includes(k)) data[k] = number(data[k] as FormDataEntryValue); }); if (kind === 'point') data.status = String(data.status || 'active'); if (kind === 'segment') data.status = String(data.status || 'planned'); if (kind === 'core') data.status = String(data.status || 'available'); mutate.mutate({ kind, data }); };
    if (hasError) return <PageErrorState message="Unable to load authoritative FIM records." onRetry={() => window.location.reload()} />;
    const rows = tab === 'cables' ? cables.data?.data ?? [] : tab === 'points' ? points.data?.data ?? [] : tab === 'segments' ? segments.data?.data ?? [] : tab === 'cores' ? cores.data?.data ?? [] : connections.data?.data ?? [];
    const columns = (tab === 'cables' ? [{ key: 'cable_code', label: 'Cable' }, { key: 'fiber_count', label: 'Fibers' }, { key: 'status', label: 'Status', render: (r: FiberCable) => <Chip size="small" label={r.status} /> }, { key: 'route_geometry_authority', label: 'Route authority' }] : tab === 'points' ? [{ key: 'name', label: 'Connection point', render: (r: ConnectionPoint) => r.name || `Point #${r.id}` }, { key: 'point_type', label: 'Type' }, { key: 'site_id', label: 'Site' }, { key: 'status', label: 'Status' }] : tab === 'segments' ? [{ key: 'fiber_cable_id', label: 'Cable' }, { key: 'sequence', label: 'Order' }, { key: 'endpoint_a_id', label: 'Endpoint A' }, { key: 'endpoint_b_id', label: 'Endpoint B' }, { key: 'status', label: 'Status' }] : tab === 'cores' ? [{ key: 'fiber_segment_id', label: 'Segment' }, { key: 'core_number', label: 'Core' }, { key: 'color_code', label: 'Color', render: (r: FiberCore) => r.color_code || '—' }, { key: 'status', label: 'Status' }] : [{ key: 'termination_a_id', label: 'Termination A' }, { key: 'termination_b_id', label: 'Termination B' }, { key: 'connection_type', label: 'Explicit splice type' }]) as unknown as Column<{ id: number }>[];
    return <Box sx={{ p: 3, maxWidth: 1600, mx: 'auto' }}><PageHeader title="Fiber Infrastructure Operations" breadcrumbs={[{ label: 'FIM' }]} actions={<Can permissions={['fim.connection-points.create', 'fim.fiber-segments.create', 'fim.fiber-cores.create', 'fim.physical-connections.create']}><Button variant="contained" startIcon={<AddIcon />} onClick={() => setOpen(true)}>Record physical work</Button></Can>} />
        <Alert severity="info" sx={{ mb: 2 }}>This workspace records explicit physical inventory and continuity only. It does not infer edges, render topology, configure network devices, or model services.</Alert>
        <Tabs value={tab} onChange={(_, value: TabName) => setTab(value)} variant="scrollable" sx={{ mb: 2 }}>{(['cables', 'points', 'segments', 'cores', 'connections', 'operations'] as TabName[]).map(x => <Tab key={x} value={x} label={x === 'points' ? 'Connection points' : x === 'connections' ? 'Physical splices' : x === 'operations' ? 'Continuity & capacity' : x} />)}</Tabs>
        {tab === 'operations' ? <Operations cores={cores.data?.data ?? []} assetId={assetId} setAssetId={setAssetId} passive={passive.data?.data ?? []} selectedCore={selectedCore} setSelectedCore={setSelectedCore} /> : <Can permission={permissions[tab]} fallback={<Alert severity="warning">You do not have permission to view these FIM records.</Alert>}><DataTable columns={columns} data={rows as Array<{ id: number }>} loading={cables.isLoading || points.isLoading || segments.isLoading || cores.isLoading || connections.isLoading} page={0} rowsPerPage={100} total={(rows as unknown[]).length} onPageChange={() => undefined} onRowsPerPageChange={() => undefined} emptyMessage="No authorized physical records found." /></Can>}
        <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><form onSubmit={submit}><DialogTitle>Record explicit physical work</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField select required name="kind" label="Record type" defaultValue="point"><MenuItem value="point">Connection point</MenuItem><MenuItem value="segment">Fiber segment</MenuItem><MenuItem value="core">Fiber core</MenuItem><MenuItem value="termination">Core termination</MenuItem><MenuItem value="connection">Physical splice</MenuItem><MenuItem value="passive">Passive optical port</MenuItem></TextField><Typography variant="caption">Use only IDs returned by the scoped lists above. The API validates company scope, endpoint ownership, ordering, and exclusive attachment rules.</Typography><TextField name="name" label="Name (connection point)" /><TextField name="point_type" label="Point type" /><TextField name="site_id" label="Site ID" type="number" /><TextField name="fiber_cable_id" label="Cable ID (segment)" type="number" /><TextField name="endpoint_a_id" label="Endpoint A ID (segment)" type="number" /><TextField name="endpoint_b_id" label="Endpoint B ID (segment)" type="number" /><TextField name="sequence" label="Segment sequence" type="number" /><TextField name="fiber_segment_id" label="Segment ID (core)" type="number" /><TextField name="core_number" label="Core number" type="number" /><TextField name="fiber_core_id" label="Core ID (termination)" type="number" /><TextField name="network_connection_point_id" label="Connection point ID" type="number" /><TextField select name="segment_end" label="Segment end" defaultValue="A"><MenuItem value="A">A</MenuItem><MenuItem value="B">B</MenuItem></TextField><TextField name="termination_a_id" label="Termination A ID (splice)" type="number" /><TextField name="termination_b_id" label="Termination B ID (splice)" type="number" /><TextField select name="connection_type" label="Splice type" defaultValue="fusion_splice"><MenuItem value="fusion_splice">Fusion splice</MenuItem><MenuItem value="mechanical_splice">Mechanical splice</MenuItem></TextField><TextField name="asset_id" label="Asset ID (passive port)" type="number" /><TextField name="port_number" label="Passive port number" /><TextField select name="port_role" label="Passive port role" defaultValue="input"><MenuItem value="input">Input</MenuItem><MenuItem value="output">Output</MenuItem></TextField><TextField select name="status" label="Status" defaultValue="active"><MenuItem value="active">Active</MenuItem><MenuItem value="planned">Planned</MenuItem><MenuItem value="available">Available</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={mutate.isPending}>Save authoritative record</Button></DialogActions></form></Dialog></Box>;
}

function Operations({ cores, assetId, setAssetId, passive, selectedCore, setSelectedCore }: { cores: FiberCore[]; assetId: string; setAssetId: (id: string) => void; passive: { id: number; port_number: string; port_role: string }[]; selectedCore: FiberCore | null; setSelectedCore: (core: FiberCore | null) => void }) {
    const [capacityKind, setCapacityKind] = useState<'cable' | 'segment' | 'splitter'>('cable'); const [capacityId, setCapacityId] = useState('');
    const capacity = useQuery({ queryKey: fimKeys.continuity(selectedCore?.id ?? 0), queryFn: () => selectedCore ? fimApi.continuity(selectedCore.id) : Promise.resolve(null), enabled: !!selectedCore });
    const capacityRead = useQuery({ queryKey: fimKeys.capacity(capacityKind, Number(capacityId) || 0), queryFn: () => fimApi.capacity(capacityKind, Number(capacityId)), enabled: Number(capacityId) > 0 });
    return <Stack spacing={3}><Box><Typography variant="h6">Ordered strand continuity</Typography><Typography variant="body2" color="text.secondary">The API returns an ordered, bounded physical-strand path. No visual graph or inferred connection is generated.</Typography><TextField select label="Fiber core" value={selectedCore?.id ?? ''} onChange={e => setSelectedCore(cores.find(c => c.id === Number(e.target.value)) ?? null)} sx={{ mt: 2, minWidth: 280 }}><MenuItem value="">Select authorized core</MenuItem>{cores.map(c => <MenuItem key={c.id} value={c.id}>Segment {c.fiber_segment_id}, core {c.core_number}</MenuItem>)}</TextField>{capacity.data && <Box component="pre" sx={{ p: 2, bgcolor: 'action.hover', overflow: 'auto' }}>{JSON.stringify(capacity.data, null, 2)}</Box>}</Box><Divider /><Box><Typography variant="h6">Derived capacity</Typography><Stack direction="row" spacing={1} sx={{ mt: 2 }}><TextField select label="Object" value={capacityKind} onChange={e => setCapacityKind(e.target.value as typeof capacityKind)}><MenuItem value="cable">Cable</MenuItem><MenuItem value="segment">Segment</MenuItem><MenuItem value="splitter">Splitter</MenuItem></TextField><TextField label="Authorized ID" value={capacityId} onChange={e => setCapacityId(e.target.value)} type="number" /></Stack>{capacityRead.data && <Box component="pre" sx={{ p: 2, bgcolor: 'action.hover', overflow: 'auto' }}>{JSON.stringify(capacityRead.data, null, 2)}</Box>}</Box><Divider /><Box><Typography variant="h6">Passive attachment inventory</Typography><TextField label="Authorized asset ID" value={assetId} onChange={e => setAssetId(e.target.value)} type="number" sx={{ mt: 2 }} />{assetId && <DataTable columns={[{ key: 'port_number', label: 'Port' }, { key: 'port_role', label: 'Role' }]} data={passive} page={0} rowsPerPage={100} total={passive.length} onPageChange={() => undefined} onRowsPerPageChange={() => undefined} emptyMessage="No passive optical ports for this authorized asset." />}</Box></Stack>;
}
