import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { DataTable } from '@/components/tables/DataTable';
import { fimApi, type FiberCore, type FiberTermination } from '../api/fim';
import { fimKeys } from '@/api/queryKeys';
import { getNetworkPorts, type NetworkPort } from '@/features/assets/api/assets';
import toast from 'react-hot-toast';

export function FimAttachmentOperations({ cores }: { cores: FiberCore[] }) {
    const client = useQueryClient();
    const [coreId, setCoreId] = useState(''); const [termination, setTermination] = useState<FiberTermination | null>(null);
    const [passiveAssetId, setPassiveAssetId] = useState(''); const [networkAssetId, setNetworkAssetId] = useState(''); const [networkPortId, setNetworkPortId] = useState('');
    const [splitterAssetId, setSplitterAssetId] = useState(''); const [inputPort, setInputPort] = useState(''); const [outputPort, setOutputPort] = useState(''); const [inputPoint, setInputPoint] = useState(''); const [outputPoint, setOutputPoint] = useState('');
    const invalidate = () => client.invalidateQueries({ queryKey: ['fim'] });
    const terminations = useQuery({ queryKey: fimKeys.terminations(Number(coreId), { per_page: 100 }), queryFn: () => fimApi.terminations(Number(coreId), { per_page: 100 }), enabled: Number(coreId) > 0 });
    const passive = useQuery({ queryKey: fimKeys.passivePorts(Number(passiveAssetId), { per_page: 100 }), queryFn: () => fimApi.passivePorts(Number(passiveAssetId), { per_page: 100 }), enabled: Number(passiveAssetId) > 0 });
    const ports = useQuery({ queryKey: ['fim', 'network-ports', networkAssetId], queryFn: () => getNetworkPorts(Number(networkAssetId), { per_page: 100 }), enabled: Number(networkAssetId) > 0 });
    const networkAttachments = useQuery({ queryKey: ['fim', 'network-port-attachments', networkPortId], queryFn: () => fimApi.networkPortAttachments(Number(networkPortId)), enabled: Number(networkPortId) > 0 });
    const passiveAttachments = useQuery({ queryKey: ['fim', 'termination-attachments', termination?.id], queryFn: () => fimApi.terminationAttachments(termination!.id), enabled: !!termination });
    const profile = useQuery({ queryKey: ['fim', 'splitter-profile', splitterAssetId], queryFn: () => fimApi.splitterProfile(Number(splitterAssetId)), enabled: Number(splitterAssetId) > 0, retry: false });
    const branches = useQuery({ queryKey: ['fim', 'splitter-branches', profile.data?.id], queryFn: () => fimApi.splitterBranches(profile.data!.id), enabled: !!profile.data });
    const action = useMutation({ mutationFn: (work: () => Promise<unknown>) => work(), onSuccess: () => { invalidate(); toast.success('Authoritative attachment updated.'); }, onError: () => toast.error('The API rejected the operation. Existing occupancy and scope are preserved.') });
    const selectedCore = cores.find(core => core.id === Number(coreId));
    return <Stack spacing={3} sx={{ mt: 3 }}><Box><Typography variant="h6">Termination attachments</Typography><Typography variant="body2" color="text.secondary">Attach only an explicit termination. Occupancy conflicts are returned by the API and are never inferred in the browser.</Typography><Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 2 }}><TextField select label="Fiber core" value={coreId} onChange={event => { setCoreId(event.target.value); setTermination(null); }} sx={{ minWidth: 250 }}><MenuItem value="">Select core</MenuItem>{cores.map(core => <MenuItem key={core.id} value={core.id}>Segment {core.fiber_segment_id}, core {core.core_number} ({core.status})</MenuItem>)}</TextField><TextField select label="Termination" value={termination?.id ?? ''} onChange={event => setTermination(terminations.data?.data.find(item => item.id === Number(event.target.value)) ?? null)} disabled={!coreId} sx={{ minWidth: 220 }}><MenuItem value="">Select termination</MenuItem>{terminations.data?.data.map(item => <MenuItem key={item.id} value={item.id}>End {item.segment_end}, NCP #{item.network_connection_point_id}</MenuItem>)}</TextField></Stack>{selectedCore && <Alert severity="info" sx={{ mt: 1 }}>Selected core #{selectedCore.core_number} belongs to segment #{selectedCore.fiber_segment_id}.</Alert>}</Box>
        {termination && <><Box><Typography variant="subtitle1">Passive optical port attachment</Typography><Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 1 }}><TextField label="Passive asset ID" type="number" value={passiveAssetId} onChange={event => setPassiveAssetId(event.target.value)} /><TextField select label="Passive port" value="" onChange={event => action.mutate(() => fimApi.attachPassive(termination.id, Number(event.target.value)))} disabled={!passive.data?.data.length} sx={{ minWidth: 260 }}><MenuItem value="">Attach an available authorized port</MenuItem>{passive.data?.data.map(port => <MenuItem key={port.id} value={port.id}>{port.port_role} {port.port_number} at NCP #{port.network_connection_point_id}</MenuItem>)}</TextField></Stack><DataTable columns={[{ key: 'passive_optical_port_id', label: 'Attached passive port' }]} data={passiveAttachments.data?.data ?? []} page={0} rowsPerPage={100} total={passiveAttachments.data?.data.length ?? 0} onPageChange={() => undefined} onRowsPerPageChange={() => undefined} actions={[{ label: 'Detach passive port', icon: <Button color="error" size="small">Detach</Button>, onClick: item => action.mutate(() => fimApi.detachPassive(item.id)) }]} emptyMessage="No passive port is attached to this termination." /></Box>
        <Box><Typography variant="subtitle1">Active network-port fiber attachment</Typography><Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 1 }}><TextField label="Network asset ID" type="number" value={networkAssetId} onChange={event => { setNetworkAssetId(event.target.value); setNetworkPortId(''); }} /><TextField select label="Network port" value={networkPortId} onChange={event => setNetworkPortId(event.target.value)} disabled={!ports.data?.data.length} sx={{ minWidth: 260 }}><MenuItem value="">Select authoritative port</MenuItem>{ports.data?.data.map((port: NetworkPort) => <MenuItem key={port.id} value={port.id}>{port.port_key}{port.name ? ` - ${port.name}` : ''}</MenuItem>)}</TextField><Button variant="outlined" disabled={!networkPortId} onClick={() => action.mutate(() => fimApi.attachNetworkPort(Number(networkPortId), termination.id))}>Attach termination</Button></Stack><DataTable columns={[{ key: 'network_port_id', label: 'Network port' }, { key: 'fiber_termination_id', label: 'Termination' }]} data={networkAttachments.data?.data ?? []} page={0} rowsPerPage={100} total={networkAttachments.data?.data.length ?? 0} onPageChange={() => undefined} onRowsPerPageChange={() => undefined} actions={[{ label: 'Disconnect active port', icon: <Button color="error" size="small">Disconnect</Button>, onClick: item => action.mutate(() => fimApi.detachNetworkPort(item.id)) }]} emptyMessage="No active fiber attachment for this selected network port." /></Box></>}
        <Box><Typography variant="h6">Splitter profile and branches</Typography><Typography variant="body2" color="text.secondary">A splitter remains an Asset. This panel manages its explicit profile, generated passive ports, and input-to-output branches.</Typography><Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 1 }}><TextField label="Splitter asset ID" type="number" value={splitterAssetId} onChange={event => setSplitterAssetId(event.target.value)} /><Button variant="outlined" disabled={!splitterAssetId || !!profile.data} onClick={() => action.mutate(() => fimApi.createSplitterProfile(Number(splitterAssetId), { input_port_count: 1, output_port_count: 8, split_ratio: '1:8' }))}>Create 1:8 profile</Button></Stack>{profile.data && <><Alert severity="info" sx={{ mt: 1 }}>Profile #{profile.data.id}: {profile.data.input_port_count} input / {profile.data.output_port_count} output, ratio {profile.data.split_ratio || 'unspecified'}.</Alert><Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ mt: 1 }}><TextField label="Input port / NCP" value={inputPort} onChange={event => setInputPort(event.target.value)} helperText="Port number" /><TextField label="Input NCP ID" type="number" value={inputPoint} onChange={event => setInputPoint(event.target.value)} /><TextField label="Output port / NCP" value={outputPort} onChange={event => setOutputPort(event.target.value)} helperText="Port number" /><TextField label="Output NCP ID" type="number" value={outputPoint} onChange={event => setOutputPoint(event.target.value)} /><Button variant="outlined" disabled={!inputPort || !outputPort || !inputPoint || !outputPoint} onClick={() => action.mutate(() => fimApi.generateSplitterPorts(profile.data!.id, { inputs: [{ port_number: inputPort, network_connection_point_id: Number(inputPoint) }], outputs: [{ port_number: outputPort, network_connection_point_id: Number(outputPoint) }] }))}>Generate ports</Button></Stack><SplitterBranches profileId={profile.data.id} branches={branches.data?.data ?? []} action={action.mutate} /></>}</Box></Stack>;
}

function SplitterBranches({ profileId, branches, action }: { profileId: number; branches: Array<{ id: number; input_port_id: number; output_port_id: number }>; action: (work: () => Promise<unknown>) => void }) {
    const [input, setInput] = useState(''); const [output, setOutput] = useState('');
    return <Box sx={{ mt: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={1}><TextField label="Input passive port ID" type="number" value={input} onChange={event => setInput(event.target.value)} /><TextField label="Output passive port ID" type="number" value={output} onChange={event => setOutput(event.target.value)} /><Button variant="outlined" disabled={!input || !output} onClick={() => action(() => fimApi.createSplitterBranch(profileId, { input_port_id: Number(input), output_port_id: Number(output) }))}>Add explicit branch</Button></Stack><DataTable columns={[{ key: 'input_port_id', label: 'Input port' }, { key: 'output_port_id', label: 'Output port' }]} data={branches} page={0} rowsPerPage={100} total={branches.length} onPageChange={() => undefined} onRowsPerPageChange={() => undefined} actions={[{ label: 'Remove branch', icon: <Button color="error" size="small">Remove</Button>, onClick: branch => action(() => fimApi.deleteSplitterBranch(branch.id)) }]} emptyMessage="No explicit splitter branches recorded." /></Box>;
}
